apiVersion: v1
kind: Service
metadata:
  name: fc-postgres
  labels:
    app: fc-postgres
  namespace: federated-catalogue
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: fc-postgres