apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-portal.fullname" . }}-keycloak-client-secret
type: Opaque
stringData:
  keycloak_client_secret: {{ .Values.demoPortal.keycloakClientSecret }}
