apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "neo4j.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neo4j.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neo4j.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-plugins
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: fc-neo4j-data
              mountPath: /plugins
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.10/apoc-4.4.0.10-all.jar -O
              curl -L https://graphdatascience.ninja/neo4j-graph-data-science-2.2.2.jar -O
              curl -L https://github.com/neo4j-labs/neosemantics/releases/download/4.4.0.2/neosemantics-4.4.0.2.jar -O
              cp -R apoc-4.4.0.10-all.jar /plugins
              cp -R neo4j-graph-data-science-2.2.2.jar /plugins
              cp -R neosemantics-4.4.0.2.jar /plugins
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "neo4j.fullname" . }}-pass-secret
                  key: auth
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "gds.*,apoc.*,n10s.*"
            - name: NEO4J_dbms_security_procedures_allowlist
              value: "gds.*,apoc.*,n10s.*"
            - name: NEO4J_dbms_connector_http_listen__address
              value: ':7474'
            - name: NEO4J_dbms_connector_bolt_listen__address
              value: ':7687'
            - name: NEO4JLABS_PLUGINS
              value: '["apoc", "graph-data-science", "n10s"]'
            - name: NEO4J_dbms_directories_plugins
              value: "plugins"
            - name: NEO4J_dbms_directories_data
              value: "data"
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http
            - containerPort: {{ .Values.service.httpsPort }}
              name: https
            - containerPort: {{ .Values.service.boltPort }}
              name: bolt
          volumeMounts:
            - name: fc-neo4j-data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fc-neo4j-data
          persistentVolumeClaim:
            claimName: {{ include "neo4j.fullname" . }}-data