apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neo4j.fullname" . }}-data
  labels:
    {{- include "neo4j.selectorLabels" . | nindent 8 }}
spec:
  {{- if .Values.storageClassName }}
    storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}