apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo4j.fullname" . }}-pass-secret
type: Opaque
stringData:
  auth: {{ .Values.neo4j.user }}/{{ .Values.neo4j.password }}
  user: "{{ .Values.neo4j.user }}"
  password: "{{ .Values.neo4j.password }}"
