apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: 7474
      name: http
    - protocol: TCP
      port: {{ .Values.service.httpsPort }}
      targetPort: 7473
      name: https
    - protocol: TCP
      port: {{ .Values.service.boltPort }}
      targetPort: 7687
      name: bolt
  selector:
    {{- include "neo4j.selectorLabels" . | nindent 4 }}
