apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fc.fullname" . }}
  labels:
    {{- include "fc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FEDERATED_CATALOGUE_VERIFICATION_SEMANTICS
              value: {{ .Values.fc.verification.semantics | quote }}
            - name: FEDERATED_CATALOGUE_VERIFICATION_SCHEMA
              value: {{ .Values.fc.verification.schema | quote }}
            - name: FEDERATED_CATALOGUE_VERIFICATION_SIGNATURES
              value: {{ .Values.fc.verification.signatures | quote }}
            - name: GRAPHSTORE_URI
              value: {{ .Values.fc.graphstoreUri }}
            - name: GRAPHSTORE_USER
              valueFrom:
                secretKeyRef:
                  name: neo4j-pass-secret
                  key: user
            - name: GRAPHSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-pass-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.fc.datasourceUrl }}
            - name: GRAPHSTORE_QUERY_TIMEOUT_IN_SECONDS
              value: {{ .Values.fc.graphstoreQueryTimeoutInSeconds | quote }}
            - name: DATASTORE_FILE_PATH
              value: /var/lib/fc-service/filestore
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: {{ .Values.fc.keycloakAuthServerUrl }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.fc.springSecurityOauth2ResourceserverJwtIssuerUri }}
            - name: KEYCLOAK_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "fc.fullname" . }}-keycloak-client-secret
                  key: keycloak_client_secret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
