# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: federated-catalogue
#   name: fc-filestore-volume
#   labels:
#     type: local
#     app: fc-service
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /mnt/shared-data/filestore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: federated-catalogue
  name: fc-filestore-claim
  labels:
    app: fc-service
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi