[project]
name = "fc-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "python-keycloak>=5.1.1",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
]
