apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-pass-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.keycloak.adminUser }}
  password: {{ .Values.keycloak.adminPassword }}
  dbUsername: {{ .Values.keycloak.dbUsername }}
  dbPassword: {{ .Values.keycloak.dbPassword }}