apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
