apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-pass-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.username}}
  password: {{ .Values.postgres.password}}
