apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: federated-catalogue
  name: fc-neo4j-data-claim
  labels:
    app: fc-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi